name: Terraform Plan

on:
  pull_request:
    branches:
      - develop
      - staging
      - main

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Read Service Environments
        id: read-environments
        run: echo "envs=$(cat service_environments.json)" >> $GITHUB_ENV

      - name: Run Terraform Plan for Each Directory
        run: |
          echo $envs | jq -c '.[]' | while read -r env; do
            name=$(echo $env | jq -r '.name')
            dir=$(echo $env | jq -r '.dir')

            echo "Running Terraform Plan for $name in $dir"
            cd $dir
            terraform init
            terraform plan
            cd -
          done
